version: "3.9"
services:
  web:
    image: "bartlomiejgora/calculator-web-react:latest"
    depends_on:
      - backend
    ports:
    - "80:80"
  backend:
    image: "bartlomiejgora/calculator-web-kotlin:latest"
    ports:
    - "8080:8080"
